#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
query_paths.py

Query call paths (DOWN callees / UP callers) from output/functions.json
generated by extract_ast.py.

NEW:
- --emit-json : export per-case decision tree + sinks + conditions as JSON

Examples:
  # DOWN paths (callees)
  python query_paths.py --func Service_Led_Main_Func
  python query_paths.py --func Service_Led_Main_Func --conds

  # UP paths (callers)
  python query_paths.py --func Service_Led_Main_Func --up --conds

  # Shortest path to a sink
  python query_paths.py --func Service_Led_Main_Func --to Wr_AllArea_BGRData --conds

  # Export per-case decision tree to JSON
  python query_paths.py --func Service_Led_Main_Func --emit-json --json-out output/led_cases.json --max-depth 12
"""

import json
import argparse
from pathlib import Path
from collections import deque, defaultdict
import re
import sys
from typing import Dict, List, Tuple, Optional, Any


# ==========================
# Default ignore list
# ==========================
DEFAULT_IGNORE_REGEX = [
    r"^IS_MASK_",
    r"^SD_Ptr_",
    r"^RamDebugDump$",
    r"^LogTest$",
    r"^print",
    r"^mem",
    r"^CLEAR_MASK",
    r"^SET_MASK",
]


def _compile_regex(pattern: Optional[str]) -> Optional[re.Pattern]:
    if not pattern:
        return None
    return re.compile(pattern)


def compile_ignore_patterns(extra_exclude: Optional[str] = None, disable_default: bool = False) -> Optional[re.Pattern]:
    patterns: List[str] = []
    if not disable_default:
        patterns.extend(DEFAULT_IGNORE_REGEX)
    if extra_exclude:
        patterns.append(extra_exclude)

    if not patterns:
        return None

    return re.compile("|".join(f"(?:{p})" for p in patterns))


# ==========================
# Load graphs
# ==========================
def load_graphs(functions_json: Path):
    if not functions_json.exists():
        raise FileNotFoundError(f"JSON not found: {functions_json}")

    data = json.loads(functions_json.read_text(encoding="utf-8"))

    # condition-aware edges
    # call_edges: caller -> [{callee, conds, loc}, ...]
    # called_by_edges: callee -> [{caller, conds, loc}, ...]
    call_edges = data.get("call_edges")
    called_by_edges = data.get("called_by_edges")

    # Basic call graph
    if "call_graph" in data and isinstance(data["call_graph"], dict):
        call_graph = data["call_graph"]
    else:
        call_graph = {}
        for f in data.get("functions", []):
            call_graph[f["function"]] = f.get("calls", [])

    # Reverse
    if "called_by" in data and isinstance(data["called_by"], dict):
        called_by = data["called_by"]
    else:
        called_by = {}
        for caller, callees in call_graph.items():
            for callee in callees:
                called_by.setdefault(callee, []).append(caller)

    functions = data.get("functions", [])
    func_names = [f.get("function") for f in functions if f.get("function")]

    return call_graph, called_by, call_edges, called_by_edges, func_names


# ==========================
# Graph iteration helpers
# ==========================
def _passes_filters(
    name: str,
    ignore_pattern: Optional[re.Pattern],
    include_re: Optional[re.Pattern],
) -> bool:
    if ignore_pattern and ignore_pattern.search(name):
        return False
    if include_re and not include_re.search(name):
        return False
    return True


def iter_children(
    graph: Dict[str, Any],
    edges_graph: Optional[Dict[str, Any]],
    node: str,
    *,
    ignore_pattern: Optional[re.Pattern] = None,
    include_re: Optional[re.Pattern] = None,
) -> List[Tuple[str, List[str]]]:
    """
    Return list of (child, conds_list).

    DOWN mode:
      node = caller, child = callee

    UP mode:
      node = callee, child = caller
    """
    out: List[Tuple[str, List[str]]] = []

    if edges_graph and node in edges_graph:
        for e in edges_graph.get(node, []):
            child = e.get("callee") or e.get("caller")
            if not child:
                continue
            if not _passes_filters(child, ignore_pattern, include_re):
                continue
            conds = e.get("conds", []) or []
            out.append((child, conds))
        return out

    for c in graph.get(node, []) or []:
        if not _passes_filters(c, ignore_pattern, include_re):
            continue
        out.append((c, []))
    return out


# ==========================
# Path finding (text mode)
# ==========================
def find_all_paths(
    graph: Dict[str, Any],
    edges_graph: Optional[Dict[str, Any]],
    root: str,
    *,
    max_depth: int = 10,
    max_paths: int = 200,
    include_re: Optional[re.Pattern] = None,
    ignore_pattern: Optional[re.Pattern] = None,
) -> List[List[Dict[str, Any]]]:
    """
    DFS enumerate paths until leaf or depth reached.

    Each path item: {"node": name, "via": [conds...]}
    where "via" are edge conditions leading into this node.
    """
    paths: List[List[Dict[str, Any]]] = []

    stack: List[Tuple[str, List[Dict[str, Any]], set]] = [
        (root, [{"node": root, "via": []}], {root})
    ]

    while stack and len(paths) < max_paths:
        node, path, seen = stack.pop()

        if len(path) >= max_depth:
            paths.append(path + [{"node": "…(max_depth)", "via": []}])
            continue

        children = iter_children(
            graph,
            edges_graph,
            node,
            ignore_pattern=ignore_pattern,
            include_re=include_re,
        )

        if not children:
            paths.append(path)
            continue

        for (c, conds) in reversed(children):
            if c in seen:
                paths.append(path + [{"node": f"↻{c}", "via": conds}])
                continue
            new_seen = set(seen)
            new_seen.add(c)
            stack.append((c, path + [{"node": c, "via": conds}], new_seen))

    return paths


def shortest_path(
    graph: Dict[str, Any],
    edges_graph: Optional[Dict[str, Any]],
    src: str,
    dst: str,
    *,
    include_re: Optional[re.Pattern] = None,
    ignore_pattern: Optional[re.Pattern] = None,
    max_depth: int = 200,
) -> Optional[List[Dict[str, Any]]]:
    """
    BFS shortest path from src to dst, with filters applied.
    """
    if src == dst:
        return [{"node": src, "via": []}]

    q = deque([(src, 0)])
    visited = {src}

    prev: Dict[str, Optional[str]] = {src: None}
    prev_cond: Dict[str, List[str]] = {src: []}

    while q:
        u, depth = q.popleft()
        if depth >= max_depth:
            continue

        for v, conds in iter_children(
            graph,
            edges_graph,
            u,
            ignore_pattern=ignore_pattern,
            include_re=include_re,
        ):
            if v in visited:
                continue
            visited.add(v)
            prev[v] = u
            prev_cond[v] = conds

            if v == dst:
                path_nodes: List[Dict[str, Any]] = [{"node": dst, "via": prev_cond[dst]}]
                cur = dst
                while prev[cur] is not None:
                    p = prev[cur]
                    path_nodes.append({"node": p, "via": prev_cond.get(p, [])})
                    cur = p
                return list(reversed(path_nodes))

            q.append((v, depth + 1))

    return None


# ==========================
# Formatting
# ==========================
def fmt_path(path: List[Dict[str, Any]], show_conds: bool = False) -> str:
    if not show_conds:
        return " -> ".join([p["node"] for p in path])

    parts: List[str] = []
    for i, p in enumerate(path):
        n = p["node"]
        if i == 0:
            parts.append(n)
            continue
        conds = p.get("via", []) or []
        if conds:
            parts.append(f"-[{' && '.join(conds)}]-> {n}")
        else:
            parts.append(f"-> {n}")
    return " ".join(parts)


# ==========================
# JSON Export: per-case decision tree
# ==========================
CASE_RE_DEFAULT = r"case\((.*?)\)"
SWITCH_RE_DEFAULT = r"switch\((.*?)\)"


def _extract_case_from_conds(conds: List[str], case_re: re.Pattern) -> Optional[str]:
    for c in conds or []:
        m = case_re.search(c)
        if m:
            return m.group(1).strip()
    return None


def _extract_switch_exprs_from_conds(conds: List[str], switch_re: re.Pattern) -> List[str]:
    out: List[str] = []
    for c in conds or []:
        m = switch_re.search(c)
        if m:
            out.append(m.group(1).strip())
    return out


def _is_sink(fn: str, sink_re: re.Pattern) -> bool:
    return bool(sink_re.search(fn))


def build_case_json(
    call_graph: Dict[str, Any],
    call_edges: Optional[Dict[str, Any]],
    root: str,
    *,
    max_depth: int,
    max_paths_per_case: int,
    include_re: Optional[re.Pattern],
    ignore_pattern: Optional[re.Pattern],
    sink_re: re.Pattern,
    case_re: re.Pattern,
    switch_re: re.Pattern,
) -> Dict[str, Any]:
    """
    Build JSON:
      {
        root,
        cases: {
          CASE_LABEL: {
            entries: [{callee, edge_conds, switch_exprs}],
            sinks: [...],
            paths: [{nodes:[...], edge_conds:[...], sink:...}, ...],
            tree: {...}
          },
          ...
        }
      }
    """
    if call_edges is None:
        raise RuntimeError("functions.json missing call_edges. Re-run extract_ast.py with condition-aware edges enabled.")

    # 1) Group root outgoing edges by case label
    root_edges = call_edges.get(root, []) or []
    case_groups: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

    for e in root_edges:
        callee = e.get("callee")
        conds = e.get("conds", []) or []
        if not callee:
            continue
        if not _passes_filters(callee, ignore_pattern, include_re):
            continue

        case_label = _extract_case_from_conds(conds, case_re) or "__NO_CASE__"
        case_groups[case_label].append({
            "callee": callee,
            "edge_conds": conds,
            "switch_exprs": _extract_switch_exprs_from_conds(conds, switch_re),
            "loc": e.get("loc"),
        })

    # Helper: iterate children (DOWN) with conds
    def children(node: str) -> List[Tuple[str, List[str]]]:
        return iter_children(
            call_graph,
            call_edges,
            node,
            ignore_pattern=ignore_pattern,
            include_re=include_re,
        )

    # 2) For each case, DFS enumerate paths from each entry callee to sinks/leaf/depth
    result_cases: Dict[str, Any] = {}

    for case_label, entries in sorted(case_groups.items(), key=lambda x: x[0]):
        paths_out: List[Dict[str, Any]] = []
        sinks_set = set()

        # tree as adjacency: key = func, value = list of edges {to, conds}
        tree_adj: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
        tree_seen_edge = set()

        def add_tree_edge(u: str, v: str, conds: List[str]):
            key = (u, v, " && ".join(conds or []))
            if key in tree_seen_edge:
                return
            tree_seen_edge.add(key)
            tree_adj[u].append({"to": v, "conds": conds or []})

        def dfs(start_callee: str, prefix_conds: List[str]):
            # stack: (node, nodes_list, edge_conds_list, depth, visited_set)
            stack = [(start_callee, [root, start_callee], [prefix_conds], 2, {root, start_callee})]

            while stack and len(paths_out) < max_paths_per_case:
                node, nodes_list, edge_conds_list, depth, visited = stack.pop()

                # stop condition: sink
                if _is_sink(node, sink_re):
                    sinks_set.add(node)
                    paths_out.append({
                        "sink": node,
                        "nodes": nodes_list,
                        "edge_conds": edge_conds_list,  # edge_conds[i] is conds for edge nodes[i]->nodes[i+1]
                    })
                    continue

                # stop condition: max depth
                if depth >= max_depth:
                    paths_out.append({
                        "sink": None,
                        "nodes": nodes_list + ["…(max_depth)"],
                        "edge_conds": edge_conds_list + [[]],
                    })
                    continue

                ch = children(node)
                if not ch:
                    # leaf
                    paths_out.append({
                        "sink": None,
                        "nodes": nodes_list,
                        "edge_conds": edge_conds_list,
                    })
                    continue

                # push children
                for (c, conds) in reversed(ch):
                    add_tree_edge(node, c, conds)

                    if c in visited:
                        # cycle
                        paths_out.append({
                            "sink": None,
                            "nodes": nodes_list + [f"↻{c}"],
                            "edge_conds": edge_conds_list + [conds],
                        })
                        continue
                    new_visited = set(visited)
                    new_visited.add(c)
                    stack.append((
                        c,
                        nodes_list + [c],
                        edge_conds_list + [conds],
                        depth + 1,
                        new_visited
                    ))

        # run dfs for each root-case entry edge
        for ent in entries:
            dfs(ent["callee"], ent["edge_conds"])

        # 3) Build a compact "tree" from adjacency by rooting at root -> entries
        # Ensure root edges included in tree as well
        for ent in entries:
            add_tree_edge(root, ent["callee"], ent["edge_conds"])

        result_cases[case_label] = {
            "entries": entries,
            "sinks": sorted(sinks_set),
            "paths": paths_out,
            "tree": {
                "root": root,
                "adj": {k: v for k, v in tree_adj.items()},
            },
        }

    return {
        "root": root,
        "max_depth": max_depth,
        "max_paths_per_case": max_paths_per_case,
        "sink_regex": sink_re.pattern,
        "case_regex": case_re.pattern,
        "switch_regex": switch_re.pattern,
        "cases": result_cases,
    }


# ==========================
# CLI
# ==========================
def build_argparser() -> argparse.ArgumentParser:
    epilog = r"""
Examples:
  # DOWN paths (callees)
  python query_paths.py --func Service_Led_Main_Func
  python query_paths.py --func Service_Led_Main_Func --conds

  # UP paths (callers)
  python query_paths.py --func Service_Led_Main_Func --up --conds

  # Shortest path to a target
  python query_paths.py --func Service_Led_Main_Func --to Wr_AllArea_BGRData --conds

  # Export per-case decision tree JSON (recommended)
  python query_paths.py --func Service_Led_Main_Func --emit-json --json-out output/led_cases.json --max-depth 12

  # Custom sinks (example: only LED write sinks)
  python query_paths.py --func Service_Led_Main_Func --emit-json --sink-regex "Wr_AllArea_BGRData|Brightness_Transfer_[RGB]" --json-out output/led_sinks.json
"""

    ap = argparse.ArgumentParser(
        prog="query_paths.py",
        description="Query call paths from output/functions.json (supports edge conditions).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=epilog,
    )

    ap.add_argument("--json", default="output/functions.json", help="Path to functions.json")
    ap.add_argument("--func", default=None, help="Root function name")
    ap.add_argument("--to", default=None, help="Find shortest path to target function")
    ap.add_argument("--up", action="store_true", help="Traverse UP (callers) instead of DOWN (callees)")

    ap.add_argument(
        "--conds",
        action="store_true",
        help="Show branch/loop/preproc conditions on edges (requires extract_ast.py to emit call_edges)",
    )

    ap.add_argument("--max-depth", type=int, default=10, help="Max path depth for enumeration / JSON DFS")
    ap.add_argument("--max-paths", type=int, default=200, help="Max number of paths to print (DFS)")
    ap.add_argument("--bfs-max-depth", type=int, default=200, help="Max depth bound for shortest path search (BFS).")

    ap.add_argument("--include", default=None, help="Only keep nodes matching this regex")
    ap.add_argument("--exclude", default=None, help="Exclude nodes matching this regex (in addition to default ignores)")
    ap.add_argument("--no-filter", action="store_true", help="Disable default ignore patterns")

    ap.add_argument("--list", action="store_true", help="List all discovered function names and exit")
    ap.add_argument("--grep", default=None, help="Filter function list by regex (works with --list)")

    # ---- JSON export flags ----
    ap.add_argument("--emit-json", action="store_true", help="Export per-case decision tree + sinks + conds as JSON")
    ap.add_argument("--json-out", default="-", help="JSON output file path, or '-' for stdout (default: '-')")
    ap.add_argument(
        "--sink-regex",
        default=r"(?:Wr_AllArea_BGRData|Brightness_Transfer_[RGB]|m_.*_formula|m_HsvToRgb.*)",
        help="Regex to decide sink functions for JSON export",
    )
    ap.add_argument("--case-regex", default=CASE_RE_DEFAULT, help="Regex to extract case label from cond strings")
    ap.add_argument("--switch-regex", default=SWITCH_RE_DEFAULT, help="Regex to extract switch(expr) from cond strings")
    ap.add_argument("--max-paths-per-case", type=int, default=200, help="Max paths collected per case (JSON export)")

    return ap


def main():
    ap = build_argparser()
    args = ap.parse_args()

    try:
        call_graph, called_by, call_edges, called_by_edges, func_names = load_graphs(Path(args.json))
    except Exception as e:
        print(f"❌ Failed to load JSON: {e}", file=sys.stderr)
        sys.exit(1)

    # list mode
    if args.list:
        grep_re = _compile_regex(args.grep)
        names = sorted(set(func_names))
        if grep_re:
            names = [n for n in names if grep_re.search(n)]
        print("\n".join(names))
        return

    root = args.func
    if not root:
        root = input("輸入 function 名稱: ").strip()
    if not root:
        print("❌ No --func provided.", file=sys.stderr)
        sys.exit(2)

    include_re = _compile_regex(args.include)
    ignore_pattern = compile_ignore_patterns(extra_exclude=args.exclude, disable_default=args.no_filter)

    # JSON export mode (DOWN only)
    if args.emit_json:
        if args.up:
            print("❌ --emit-json currently supports DOWN (callees) only. Remove --up.", file=sys.stderr)
            sys.exit(3)

        sink_re = re.compile(args.sink_regex)
        case_re = re.compile(args.case_regex)
        switch_re = re.compile(args.switch_regex)

        payload = build_case_json(
            call_graph=call_graph,
            call_edges=call_edges,
            root=root,
            max_depth=args.max_depth,
            max_paths_per_case=args.max_paths_per_case,
            include_re=include_re,
            ignore_pattern=ignore_pattern,
            sink_re=sink_re,
            case_re=case_re,
            switch_re=switch_re,
        )

        out_text = json.dumps(payload, indent=2, ensure_ascii=False)

        if args.json_out == "-" or args.json_out.strip() == "":
            print(out_text)
        else:
            out_path = Path(args.json_out)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(out_text, encoding="utf-8")
            print(f"✅ Wrote JSON: {out_path}")
        return

    # Normal path query mode
    graph = called_by if args.up else call_graph
    edges_graph = called_by_edges if args.up else call_edges
    direction = "UP (callers)" if args.up else "DOWN (callees)"

    # shortest path mode
    if args.to:
        path = shortest_path(
            graph,
            edges_graph,
            root,
            args.to,
            include_re=include_re,
            ignore_pattern=ignore_pattern,
            max_depth=args.bfs_max_depth,
        )
        if not path:
            print(f"❌ 找不到 path: {root} -> {args.to}")
            return
        print("✅ Shortest path:")
        print("  " + fmt_path(path, show_conds=args.conds))
        return

    # enumerate paths
    paths = find_all_paths(
        graph,
        edges_graph,
        root,
        max_depth=args.max_depth,
        max_paths=args.max_paths,
        include_re=include_re,
        ignore_pattern=ignore_pattern,
    )

    print(f"\n🌲 Paths {direction} from {root}\n")
    for i, p in enumerate(paths, 1):
        print(f"{i:03d}: " + fmt_path(p, show_conds=args.conds))


if __name__ == "__main__":
    main()